/* Allegro datafile object indexes, produced by grabber v3.0 + WIP */
/* Datafile: c:\mygames\castle\data.dat */
/* Date: Sun Sep 30 11:05:23 2001 */
/* Do not hand edit! */

#define BLANK                            0        /* BMP  */
#define CHARACTER                        1        /* BMP  */
#define FLOOR                            2        /* BMP  */
#define ITEM000                          3        /* BMP  */
#define ITEM001                          4        /* BMP  */
#define ITEM002                          5        /* BMP  */
#define ITEM003                          6        /* BMP  */
#define ITEM004                          7        /* BMP  */
#define ITEM005                          8        /* BMP  */
#define ITEM006                          9        /* BMP  */
#define ITEM007                          10       /* BMP  */
#define ITEM008                          11       /* BMP  */
#define ITEM009                          12       /* BMP  */
#define ITEM010                          13       /* BMP  */
#define ITEM011                          14       /* BMP  */
#define ITEM012                          15       /* BMP  */
#define ITEM013                          16       /* BMP  */
#define ITEM014                          17       /* BMP  */
#define ITEM015                          18       /* BMP  */
#define ITEM016                          19       /* BMP  */
#define ITEM017                          20       /* BMP  */
#define ITEM018                          21       /* BMP  */
#define ITEM019                          22       /* BMP  */
#define ITEM020                          23       /* BMP  */
#define ITEM021                          24       /* BMP  */
#define MON0000                          25       /* BMP  */
#define MON0001                          26       /* BMP  */
#define MON0002                          27       /* BMP  */
#define MON0003                          28       /* BMP  */
#define MON0004                          29       /* BMP  */
#define MON0005                          30       /* BMP  */
#define MON0006                          31       /* BMP  */
#define MON0007                          32       /* BMP  */
#define MON1000                          33       /* BMP  */
#define MON1001                          34       /* BMP  */
#define MON1002                          35       /* BMP  */
#define MON1003                          36       /* BMP  */
#define MON1004                          37       /* BMP  */
#define MON1005                          38       /* BMP  */
#define MON1006                          39       /* BMP  */
#define MON1007                          40       /* BMP  */
#define MON2000                          41       /* BMP  */
#define MON2001                          42       /* BMP  */
#define MON2002                          43       /* BMP  */
#define MON2003                          44       /* BMP  */
#define MON2004                          45       /* BMP  */
#define MON2005                          46       /* BMP  */
#define MON2006                          47       /* BMP  */
#define MON2007                          48       /* BMP  */
#define MON3000                          49       /* BMP  */
#define MON3001                          50       /* BMP  */
#define MON3002                          51       /* BMP  */
#define MON3003                          52       /* BMP  */
#define MON3004                          53       /* BMP  */
#define MON3005                          54       /* BMP  */
#define MON3006                          55       /* BMP  */
#define MON3007                          56       /* BMP  */
#define MON4000                          57       /* BMP  */
#define MON4001                          58       /* BMP  */
#define MON4002                          59       /* BMP  */
#define MON4003                          60       /* BMP  */
#define MON4004                          61       /* BMP  */
#define MON4005                          62       /* BMP  */
#define MON4006                          63       /* BMP  */
#define MON4007                          64       /* BMP  */
#define MON5000                          65       /* BMP  */
#define MON5001                          66       /* BMP  */
#define MON5002                          67       /* BMP  */
#define MON5003                          68       /* BMP  */
#define MON5004                          69       /* BMP  */
#define MON5005                          70       /* BMP  */
#define MON5006                          71       /* BMP  */
#define MON5007                          72       /* BMP  */
#define MON6000                          73       /* BMP  */
#define MON6001                          74       /* BMP  */
#define MON6002                          75       /* BMP  */
#define MON6003                          76       /* BMP  */
#define MON6004                          77       /* BMP  */
#define MON6005                          78       /* BMP  */
#define MON6006                          79       /* BMP  */
#define MON6007                          80       /* BMP  */
#define MON7000                          81       /* BMP  */
#define MON7001                          82       /* BMP  */
#define MON7002                          83       /* BMP  */
#define MON7003                          84       /* BMP  */
#define MON7004                          85       /* BMP  */
#define MON7005                          86       /* BMP  */
#define MON7006                          87       /* BMP  */
#define MON7007                          88       /* BMP  */
#define MY_FONT                          89       /* FONT */
#define TILE000                          90       /* BMP  */
#define TILE001                          91       /* BMP  */
#define TILE002                          92       /* BMP  */
#define TILE003                          93       /* BMP  */
#define TILE004                          94       /* BMP  */
#define TILE005                          95       /* BMP  */
#define TILE006                          96       /* BMP  */
#define TILE007                          97       /* BMP  */
#define TILE008                          98       /* BMP  */
#define TILE009                          99       /* BMP  */
#define TILE010                          100      /* BMP  */
#define TILE011                          101      /* BMP  */
#define TILE012                          102      /* BMP  */
#define TILE013                          103      /* BMP  */
#define TILE014                          104      /* BMP  */
#define TILE015                          105      /* BMP  */
#define TILE016                          106      /* BMP  */
#define TILE017                          107      /* BMP  */
#define TILE018                          108      /* BMP  */
#define TILE019                          109      /* BMP  */

